version: "3"

services:
  app1:
    image: myapp:v2
    container_name: app1
    ports:
      - 8888:8080

  app2:
    image: myapp:v2
    container_name: app2
    ports:
      - 8889:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
